apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongo
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongo
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      enableServiceLinks: false
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args: ["--replSet", "rs0", "--bind_ip_all"]
          ports:
            - name: mongo
              containerPort: 27017
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mongo.storage }}
